# Set theme
remote_theme: daviddarnes/garth

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-paginate
- jekyll-remote-theme

# Site settings
url: 'https://brandonkatzir.github.io'
baseurl: ''
title: 'behind the stacks'
description: 'libraries, technology, digital culture'
permalink: pretty
logo: "/logo.jpg"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Collections
collections:
  posts:
    title: behind the stacks
    output: true
    description: libraries, technology, digital culture
